Feature/simurai endpoint
fusion-oss/simurai-core pull request #7
Opened 2022-08-01 08:33 UTC by rutuja-botre

FUS-993 : Endpoint API building based on endpoint name in the database.
Filtering events from the event endpoint mapping with Simurai endpoint name only.

2022-08-01 12:54 UTC, ravi-zadpide requested changes

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/EventRoute.java
>  public class EventRoute extends RouteBuilder {
USE google style formatter for source code

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/EventRoute.java
> +        log.info("Rest with endpointName would be created : ", endpointName);
{} is missing rephrase the log statement.

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/EventRoute.java
> +                        log.info("Fetch event with the following url has been created : {}", exchange.getIn().getHeaders().get(HTTP_URL));
remove this log statement

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/EventRoute.java
> +                                log.info("Trigger event with the following url has been created", (String) exchange.getIn().getHeaders().get(HTTP_URL));
remove this log statement

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/common/constant/SimuraiConstants.java
> +  public static final String ENDPOINT_NAME = "simurai";
rename to SIMURAI_ENDPOINT

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/common/constant/SimuraiConstants.java
> +  public static final String DEFAULT_URL = "events";
rename to EVENT_URL

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/bean/EventBean.java
> +            .filter(e -> e.getEndpointName().equals(ENDPOINT_NAME))
Call "Optional#isPresent()" before accessing the value.

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/bean/EventBean.java
> +    String name = null;
declare local variables where it is being used for the first time.

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/bean/EventBean.java
> +    for (final Map eventsMap : endpointEvents) {
Map is a raw type. References to generic type Map<K,V> should be parameterized

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/bean/EventBean.java
> +      if (simuraiConfig.getEventByAliasName(name).isPresent()) {
extract to local variable simuraiConfig.getEventByAliasName(name)

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/bean/EventBean.java
> +        events.add(buildEventDto(simuraiConfig.getEventByAliasName(name).get()));
Call "Optional#isPresent()" before accessing the value.

2022-08-01 12:54 UTC, ravi-zadpide commented on src/main/java/com/scoperetail/simurai/core/application/route/event/EventRoute.java
> +        final String endpointName =
rename endpointName to eventURL

2022-08-01 13:32 UTC, PriyadharishiniM commented on src/main/java/com/scoperetail/simurai/core/common/constant/SimuraiConstants.java
> +  public static final String ENDPOINT_NAME = "simurai";
ENDPOINT_NAME  is used in both the places
EventRoute: to fetch the endpoint URL as per this endpointName
EventBean.fetchEvent(): to retrieve the event list with this endpointName
So that we have used common name for this. 

Do we need to create two constant or shall we keep as a common constant.

2022-08-03 14:03 UTC, ravi-zadpide approved these changes
Approved

2022-08-03 14:03 UTC, merged